import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Connect from "@/components/Connect";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Foundax Company",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`h-fit w-full `}>
        <Navbar/>
        <div className="md:pt-[100px] max-sm:pt-[83px]">
            {children}
        </div>
        <Connect/>
        <Footer/>
       </body>
    </html>
  );
}
